# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'my_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for my_ios
  
  flutter_application_path = '../flutter_module'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

  install_flutter_engine_pod
  install_flutter_plugin_pods flutter_application_path
  

end
